theme: jekyll-theme-cayman
title: Manoj Mukkamala
description: Data Platform Architect & Engineering Leader
google_analytics: 
# Adding custom metadata for the theme
company: Shipt
role: Data Engineering Manager
